#!/bin/echo Use "./mkroot.sh  gcc-6.3.0"

echo === download source

# download 928ab552666ee08eed645ff20ceb49d139205dea \
#   http://ftp.gnu.org/gnu/binutils/binutils-2.27.tar.bz2

echo === Native build static binutils

echo ${CROSS_COMPILE}
echo $TARGET
echo $OUTPUT
echo $ROOT
echo $HOST
env

v2=${CROSS_COMPILE::-1}

echo $v2

COMPILE_FOR_ARM="y"
COMPILE_FOR_x86="y"
COMPILE_FOR_ARCHES=""
echo $COMPILE_FOR_ARCHES
if [[ $COMPILE_FOR_x86 == y* ]]; then
  COMPILE_FOR_ARCHES="$COMPILE_FOR_ARCHES i686:: i486:: x86_64:: x86_64@x32:x32:"
fi
if [[ $COMPILE_FOR_ARM == y* ]]; then
  COMPILE_FOR_ARCHES="$COMPILE_FOR_ARCHES armv4l:eabihf:\"--with-arch=armv5t --with-float=soft\" armv5l:eabihf:--with-arch=armv5t armv7l:eabihf:--with-arch=armv7-a \"armv7m:eabi:--with-arch=armv7-m --with-mode=thumb --disable-libatomic --enable-default-pie\" armv7r:eabihf:\"--with-arch=armv7-r --enable-default-pie\" aarch64:eabi:"
fi

echo $COMPILE_FOR_ARCHES

for i in $COMPILE_FOR_ARCHES
do
  echo $i
done
