#!/bin/echo Use "./mkroot.sh  toolchain"

[ -z "$TARGET" ] && TARGET="${CROSS_COMPILE::-1}"
[ -z "$TARGET" ] && TARGET="$(uname -m)"

[ -z "$HOST" ] && HOST="$(uname -m)"


echo === download source

download 6e472ddae565a2b1447e6f2393809bb8799982cf \
  http://ftp.gnu.org/gnu/binutils/binutils-2.27.tar.bz2

download 9dc6981197a7d92f339192eea974f5eca48fcffe \
  http://ftp.gnu.org/gnu/gmp/gmp-6.1.2.tar.xz

download b8be66396c726fdc36ebb0f692ed8a8cca3bcc66 \
  https://ftp.gnu.org/gnu/mpc/mpc-1.0.3.tar.gz

download c0fab77c6da4cb710c81cc04092fb9bea11a9403 \
  http://www.mpfr.org/mpfr-3.1.5/mpfr-3.1.5.tar.xz

download 928ab552666ee08eed645ff20ceb49d139205dea \
  http://ftp.gnu.org/gnu/gcc/gcc-6.3.0/gcc-6.3.0.tar.bz2

download 5fff5a94ef4470bf48fe1b79093185f19f5c827a \
  http://ftp.gnu.org/gnu/glibc/glibc-2.25.tar.xz

echo === Native build static binutils

setupfor binutils

rm -rf build && mkdir build && cd build &&
CC=${CROSS_COMPILE}cc LD=${CROSS_COMPILE}ld AS=${CROSS_COMPILE}as ../configure --prefix=${ROOT} \
  --with-sysroot=${ROOT} --with-lib-path=${OUTPUT}/lib --build ${HOST} --host ${TARGET} \
  --target=${TARGET} --disable-nls --disable-werror --enable-static && make LDFLAGS=-static -j $(nproc) || exit 1

case $(uname -m) in
  x86_64) mkdir -v ${OUTPUT}/lib && ln -sv ${OUTPUT}/lib ${OUTPUT}/lib64 ;;
esac

make install -j4 || exit 1
