#!/bin/echo Use "./mkroot.sh  toolchain"

[ -z "$TARGET" ] && TARGET="${CROSS_COMPILE::-1}"
[ -z "$TARGET" ] && TARGET="$(uname -m)"

[ -z "$HOST" ] && HOST="$(uname -m)"


echo === download source

download 6e472ddae565a2b1447e6f2393809bb8799982cf \
  http://ftp.gnu.org/gnu/binutils/binutils-2.27.tar.bz2

download 9dc6981197a7d92f339192eea974f5eca48fcffe \
  http://ftp.gnu.org/gnu/gmp/gmp-6.1.2.tar.xz

download b8be66396c726fdc36ebb0f692ed8a8cca3bcc66 \
  https://ftp.gnu.org/gnu/mpc/mpc-1.0.3.tar.gz

download c0fab77c6da4cb710c81cc04092fb9bea11a9403 \
  http://www.mpfr.org/mpfr-3.1.5/mpfr-3.1.5.tar.xz

download 928ab552666ee08eed645ff20ceb49d139205dea \
  http://ftp.gnu.org/gnu/gcc/gcc-6.3.0/gcc-6.3.0.tar.bz2

download 5fff5a94ef4470bf48fe1b79093185f19f5c827a \
  http://ftp.gnu.org/gnu/glibc/glibc-2.25.tar.xz

echo === Native build static binutils

setupfor binutils

rm -rf build && mkdir build && cd build &&
CC=${CROSS_COMPILE}cc LD=${CROSS_COMPILE}ld AS=${CROSS_COMPILE}as ../configure --prefix=${ROOT} \
  --with-sysroot=${ROOT} --with-lib-path=${OUTPUT}/lib --build ${HOST} --host ${TARGET} \
  --target=${TARGET} --disable-nls --disable-werror --enable-static && make LDFLAGS=-static -j $(nproc) || exit 1

case $(uname -m) in
  x86_64) mkdir -v ${OUTPUT}/lib && ln -sv ${OUTPUT}/lib ${OUTPUT}/lib64 ;;
esac

make install -j4 || exit 1
cleanup

echo === Native build static gcc

setupfor binutils

tar -xf ../mpfr-3.1.5.tar.xz
mv -v mpfr-3.1.5 mpfr
tar -xf ../gmp-6.1.2.tar.xz
mv -v gmp-6.1.2 gmp
tar -xf ../mpc-1.0.3.tar.gz
mv -v mpc-1.0.3 mpc

for file in gcc/config/{linux,i386/linux{,64}}.h
do
  cp -uv $file{,.orig}
  sed -e "s@/lib\(64\)\?\(32\)\?/ld@${ROOT}&@g" \
      -e "s@/usr@/${ROOT}@g" $file.orig > $file
  echo "
#undef STANDARD_STARTFILE_PREFIX_1
#undef STANDARD_STARTFILE_PREFIX_2
#define STANDARD_STARTFILE_PREFIX_1 \"${ROOT}/lib\"
#define STANDARD_STARTFILE_PREFIX_2 \"\"" >> $file
  touch $file.orig
done

case $(uname -m) in
  x86_64)
    sed -e '/m64=/s/lib64/lib/' \
        -i.orig gcc/config/i386/t-linux64
 ;;
esac

mkdir build
cd build

../configure                                       \
    --target=${TARGET}                             \
    --build=${HOST}                                \
    --host=${TARGET}                               \
    --prefix=/tools                                \
    --with-glibc-version=2.11                      \
    --with-sysroot=$ROOT                           \
    --with-newlib                                  \
    --without-headers                              \
    --with-local-prefix=/tools                     \
    --with-native-system-header-dir=/tools/include \
    --disable-nls                                  \
    --disable-shared                               \
    --disable-multilib                             \
    --disable-decimal-float                        \
    --disable-threads                              \
    --disable-libatomic                            \
    --disable-libgomp                              \
    --disable-libmpx                               \
    --disable-libquadmath                          \
    --disable-libssp                               \
    --disable-libvtv                               \
    --disable-libstdcxx                            \
    --enable-languages=c,c++ && make -j $(nproc) && make install || exit 1
